### ISSUE TITLE
Newtonsoft.Json dependency error

### ISSUE THREAD

**Issue by markwemekamp** [MultiSafepay/.Net#5] opened 2017-05-24 07:34 UTC
Hi,
I installed MultiSafepay through nuget and it restored the minimal version of Newtonsoft.Json library (6.0.6) in my project. 
As soon as my code hits the MultiSafepayClient I get the following Exception

> An exception of type 'System.IO.FileLoadException' occurred in MultiSafepay.dll but was not handled in user code
> Additional information: Kan bestand of assembly Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed of een van de afhankelijkheden hiervan niet laden. De manifestdefinitie van de gevonden assembly komt niet overeen met de assembly-verwijzing. (Uitzondering van HRESULT: 0x80131040)

It appears the code is dependent on version 8.0 of Newtonsoft.Json, is this correct?

**Comment by markwemekamp** [comment] 2017-05-24 07:56
I did a test by downgrading the MultiSafepay package to version 5.0 (prior to [this](https://github.com/MultiSafepay/.Net/commit/62623f4cbb0119440416d6287ff73350c55d0a40) commit) and now my code works, so I think you'll have to update the nuspec file of the package.

**Comment by JonkRuud** [comment] 2017-05-24 08:17
@iexperto can you look into this one.

**Comment by iexperto** [comment] 2017-05-26 12:06
@markwemekamp thank you, I just updated Nuget to >= Newtonsoft.Json 8.0.2

**Comment by Tristanosi** [comment] 2018-11-12 09:05
This issue seems te remain with Newtonsoft 11.0.2 and MultiSafePay 0.7.2, is there a solution?

**Comment by iexperto** [comment] 2018-11-12 13:12
@Tristanosi , can you please provide more info, errors etc... about the issue you are having?
In https://www.nuget.org/packages/MultiSafepay/0.6.12
We were forced to upgrade to make it compatible with Compatible with .net core

**Comment by Tristanosi** [comment] 2018-11-12 15:14
@iexperto I reinstalled MultiSafePay and updated my web.config (it contained old reference to Newtonsoft 6.0.0.0). The issue is fixed now, I don't believe the error was caused by MultiSafePay

**Comment by iexperto** [comment] 2018-11-13 07:15
Closing issue as main problem was fixed on May 26, 2017

**Closed by iexperto** 2018-11-13 07:15 UTC
